name: Github Actions

on: [push, pull_request]

jobs:
  host_x86:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx_compiler: [g++-10, clang++-11]
    steps:
      - name: checkout code
        uses: actions/checkout@v3.0.2
      - name: build artifact
        env:
          CXX: ${{ matrix.cxx_compiler }}
        run: |
          sh .ci/cross-tool.sh
          make check
          sh .ci/cross-check.sh

  host_x86_win:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - { cxx_compiler: g++,     sys: ucrt64 }
          - { cxx_compiler: clang++, sys: clang64 }
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: make
          pacboy: cc:p
      - name: checkout code
        uses: actions/checkout@v3.0.2
      - name: build artifact
        shell: msys2 {0}
        env:
          CXX: ${{ matrix.cxx_compiler }}
        run: make check

  host_arm:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [armv7, aarch64]
        cxx_compiler: [g++-10, clang++-11]
    steps:
      - name: checkout code
        uses: actions/checkout@v3.0.2
      - name: build artifact
        # The Github Action for non-x86 CPU
        # https://github.com/uraimo/run-on-arch-action
        uses: uraimo/run-on-arch-action@v2.2.0
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          env: |
            CXX: ${{ matrix.cxx_compiler }}
          install: |
            apt-get update -q -y
            apt-get install -q -y "${{ matrix.cxx_compiler }}" make
          run: make check

  coding_style:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3.0.2
      - name: style check
        run: |
            sudo apt-get install -q -y clang-format-12
            sh .ci/check-format.sh
        shell: bash
